'use strict'

//Mixes 2 generator using a factor to blend them
class MixGenerator extends Generator{

    //2 generator and a blending rule, must accept 
    //the 2 displacement generated by the 2 generators plus the time
    //and return a final value
    constructor(generator1, generator2, blendingRule){
        super()

        this.generator1 = generator1;
        this.generator2 = generator2;
        this.blendingRule = blendingRule;
    }

    displacementFor(i, j, time){
        var displacement1 = this.generator1.displacementFor(i,j,time);
        var displacement2 = this.generator2.displacementFor(i, j, time);
        var value = this.blendingRule(displacement1, displacement2, time);
        return value;
    }

}